package com.nicosb.uni.bloom_join;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;

/**
 * CustomLog allows custom logging. I.e. disabling console output and enable logging into a file.
 * Furthermore, this class measures the amount of traffic generated by storing the stream into a file.
 * The size of the file csf indicates the overall traffic.
 * 
 * @author Nico
 *
 */
public class CustomLog {
	public static boolean printToConsole = true;
	public static boolean printToFile = false;
	public static String logFile = "log.txt";
	public static String cache_size_file = "csf";
	
	public static <T> void println(T str){
		if(printToConsole){
			System.out.println(str);
		}
		if(printToFile){
			try {
				PrintWriter out = new PrintWriter(new FileWriter(logFile, true));
				out.write(str + "\n");
				out.close();
			} catch (FileNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} 
		}
	}
	
	public static <T> void print(T str){
		if(printToConsole){
			System.out.print(str);
		}
		if(printToFile){
			try {
				PrintWriter out = new PrintWriter(new FileWriter(logFile, true));
				out.write(String.valueOf(str));
				out.close();
			} catch (FileNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}	
	public static <T> void println(T str, boolean forceConsole){
		if(forceConsole || printToConsole){
			System.out.println(str);
		}
		if(printToFile){
			try {
				PrintWriter out = new PrintWriter(new FileWriter(logFile, true));
				out.write(str + "\n");
				out.close();
			} catch (FileNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} 
		}
	}
	
	public static <T> void print(T str, boolean forceConsole){
		if(forceConsole || printToConsole){
			System.out.print(str);
		}
		if(printToFile){
			try {
				PrintWriter out = new PrintWriter(new FileWriter(logFile, true));
				out.write(String.valueOf(str));
				out.close();
			} catch (FileNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

	/**
	 * Stores the object into a file, such that the traffic can be read later on.
	 * 
	 * @param o the object to be written
	 */
	public static void sizeLog(Object o){
		try {
			FileOutputStream fis = new FileOutputStream(cache_size_file, true);
			ObjectOutputStream oos = new ObjectOutputStream(fis);
			oos.writeObject(o);
			oos.close();
			fis.close();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}	
	}
	
	public static long getTraffic(boolean delete){
		File f = new File(cache_size_file);
		long size = f.exists() ? f.length() : 0;
		if(size > 0 && delete){
			f.delete();
		}
		return size;
	}
}
